[Design] 상세페이지 메인 UI 구현
Honzapda/Honzapda_iOS pull request #13
Opened 2024-03-17 08:42 UTC by 0Hooni

## 🔥 PR 타입 (하나 이상 선택)
- [ ] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## 🔗 연결된 이슈
- Connected: #7
- [ ] 이슈 해결 여부

## 📄 작업 내용
- 상세 페이지 메인의 전반적인 UI 구현

|    구현 내용    |   15 pro   |
| :-------------: | :----------: |
| 상세페이지 메인 | <img src = "https://github.com/Honzapda/Honzapda_iOS/assets/37678646/47e42383-1143-4c94-be16-17ab95f412ec)" width ="250"> |

## 💻 주요 코드 설명

## 📚 참고자료

## 👀 기타 더 이야기해볼 점
- SwiftUI가 익숙하지 않아서 뭔가 개선점이 많을것 같다 생각하는데 보이시는거 있으시면 의견 과감하게 내주시면 정말 감사하겠습니다.
- 폰트 익스텐션과 관련된 부분에 대해 좀 정립을 더 해볼 필요가 있다 생각합니다.
- 아키텍처 패턴은 해당 PR 이후 다음 이슈와 함께 적용할 예정입니다.

2024-03-18 06:05 UTC, youz2me commented
PR 좀 더 자세히 적어주실 수 있을까욥 ...? 🥹

2024-03-18 19:48 UTC, youz2me requested changes
P1: 컴포넌트 사이마다 공백 추가가 필요할 것 같습니다!

2024-03-18 19:48 UTC, youz2me commented on Honzapda/Global/Resources/Assets.xcassets/Cafe/icon_home_crowd_high.imageset/Contents.json
> +    "version" : 1
P2 : 벡터 이미지 추가하실 때 오른쪽 인스펙터에서 single scale로 체크해주시면 좋을 것 같습니다!

2024-03-18 19:48 UTC, youz2me commented on Honzapda/Presentation/Cafe/DetailPageMain.swift
> +    }
P3 : 오 ... 이렇게 struct로 빼서 body 깔끔하게 유지하는 거 너무 좋은 것 같아요 !! 👍

2024-03-18 19:48 UTC, youz2me commented on Honzapda/Presentation/Cafe/DetailPageMain.swift
> +            Image("Cafe/thumbnail_cafe_detail")
이미지 이름에 `Cafe/`가 들어가나요? 아니면 경로 때문에 적어두신건가요 ...??

2024-03-18 19:48 UTC, youz2me commented on Honzapda/Presentation/Cafe/DetailPageMain.swift
> +                        )
overlay 쓴거 처음봐요 !! 신기 ...

2024-03-18 19:48 UTC, youz2me commented on Honzapda/Presentation/Cafe/DetailPageMain.swift
> +    var atmosphere: String?
P2: 나중에 MVVM 리팩토링 하실 때 모델로 만들어서 빼도 좋을 것 같아요!

2024-03-19 02:58 UTC, 0Hooni commented on Honzapda/Presentation/Cafe/DetailPageMain.swift
> +            Image("Cafe/thumbnail_cafe_detail")
폴더링을 해놨는데, 이게 아마 [맥구-홈 화면] 작업영역에 있는 Assets이랑 겹치는 Assets이라 구분될 수 있게 하려고 했습니다...!

2024-03-19 04:36 UTC, youz2me commented on Honzapda/Presentation/Cafe/DetailPageMain.swift
> +            Image("Cafe/thumbnail_cafe_detail")
아아 확인했습니다 !! 👍 나중에 어셋 중복 관리도 같이 이야기해보면 좋을 것 같아요 🤩

2024-03-20 06:00 UTC, 0Hooni commented
> 고생하셨습니다! 978줄 ... 대단하네요
> 
> P1: 컴포넌트 사이마다 공백 추가가 필요할 것 같습니다!

말씀주신 리뷰내용 반영했습니다☺️

2024-03-20 06:09 UTC, youz2me approved these changes
LGTM
확인했습니다 !! 고생하셨어요 짱 👍

2024-03-23 09:26 UTC, AIsiteru98 approved these changes
수고했어요 형! 잘 쉬다 오십쇼

2024-03-23 09:26 UTC, AIsiteru98 commented on Honzapda/Presentation/Cafe/DetailPageMain.swift
> +    var cafeIntroduce: String?      // 카페 한줄 소개
이 정보들 따로 스트럭트로 뺴서 관리하는 거 추천합니다. api 명세서에 나와 있어요

2024-03-23 09:26 UTC, AIsiteru98 commented on Honzapda/Presentation/Cafe/DetailPageMain.swift
> +                                .foregroundColor(.gray06)
추후 유진이가 사용한 하이라이트 방법 사용해도 괜찮을 것 같아요

2024-03-23 09:26 UTC, AIsiteru98 commented on Honzapda/Presentation/Cafe/DetailPageMain.swift
설마 이 모든 코드가 한 파일 안에 있는건가요? 리뷰에서 보기는 그런데 만약 그러면 분할하는게 좋을 거 같슴다

2024-03-23 09:53 UTC, AIsiteru98 commented
컨플릭트 해결 해야한대요 형

2024-03-23 09:53 UTC, AIsiteru98 commented
> 컨플릭트 해결 해야한대요 형

그래서 머지 못했습니다

2024-03-23 14:03 UTC, 0Hooni commented on Honzapda/Presentation/Cafe/DetailPageMain.swift
MVVM패턴 조만간 이슈 생성해서 수정할 예정입니다!

2024-03-23 14:13 UTC, 0Hooni commented on Honzapda/Presentation/Cafe/DetailPageMain.swift
> +    var cafeIntroduce: String?      // 카페 한줄 소개
다음 MVVM 패턴 적용때 같이 적용하도록 하겠습니다☺️

2024-03-23 14:14 UTC, merged