Design/#24 searchview UI
Honzapda/Honzapda_iOS pull request #30
Opened 2024-05-09 10:55 UTC by AIsiteru98

## 🔥 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## 🔗 연결된 이슈

- Connected: #24 
- [x] 이슈 해결 여부

## 📄 작업 내용

- 최근 검색어 삭제 기능
- 전반적인 UI
- 화면이동 기능
- 결과 표출을 위한 셀 뷰 

|    구현 내용    |   15 pro   |
| :-------------: | :----------: |
| GIF |  
![화면-기록-2024-05-09-오후-7 40 19](https://github.com/Honzapda/Honzapda_iOS/assets/132365672/898760bf-60b3-4cf4-bbb8-20209d40556b)
|

## 💻 주요 코드 설명

`SearchMainView.swift`
- 검색창 선택시 텍스트필드 초기화 및 페이지 이동
```swift
@ViewBuilder
    private func searchWindow() -> some View { // 검색창
        Text(placeholderText)
            .font(.sCoreDream(.medium, size: 14))
            .foregroundStyle(.primary04)
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(20)  // 텍스트 필드 내부에 패딩 추가
            .background(
                RoundedRectangle(cornerRadius: 20)  // 둥근 사각형 배경
                    .strokeBorder(.primary05, lineWidth: 1)  // 테두리 색상 및 두께 지정
                    .background(RoundedRectangle(cornerRadius: 20).fill(Color.white))  // 테두리 내부를 흰색으로 채움
                    .onTapGesture {
                        searchViewModel.searchWord = ""
                        searchViewModel.convertSearchPage.toggle()
                    }
            )
            .overlay(
                Image("icon_search_search_fill")  // 시스템 아이콘 사용
                    .padding(.trailing, 20)
                , alignment: .trailing  // 오른쪽 정렬
            )
            .padding()  // 외부 패딩으로 뷰 주변 간격 추가
    }
```

- 최근 검색어 선택 시 검색페이지로 이동하며, 검색어를 해당 버튼의 이름으로 변경한다
```swift
@ViewBuilder
    private func recentlySerached(edit: Bool, name: String) -> some View { // 최근 검색어 빌더
        HStack {
            if edit {
                Button(action: {
                    // "X" 버튼 동작을 여기에 정의합니다.
                    print("Delete tapped! \(name)")
                    if let index = searchViewModel.recentSearchWord.firstIndex(of: name) {
                        searchViewModel.recentSearchWord.remove(at: index)
                    }
                }) {
                    Image("icon_search_xbutton_fill")
                }
                .padding(.leading, 8) // 버튼에 패딩 추가
            } else {
                Spacer()
                    .frame(width: 0)
                    .padding(.leading, 16)
            }
            Button {
                searchViewModel.searchWord = name
                searchViewModel.convertSearchPage = true
            } label: {
                Text(name)
                    .multilineTextAlignment(.center)
                    .font(.sCoreDream(.medium, size: 14))
                    .foregroundColor(.primary03)
                    .padding(.vertical, 8)
                    .padding(.trailing)
            }

            
        }
        .background(
            RoundedRectangle(cornerRadius: 20)
                .strokeBorder(.primary04, lineWidth: 1)
                .background(.white)
        )
    }
```
`SearchView.swift`
- 필터의 열거형 선언과 스위치문을 통한 필터 생성
```swift
enum FilterOption {
    case none, distances, reviewCount, saved, recommended
}

private func filterGenerator(filter: FilterOption, selection: FilterOption) -> some View {
        switch filter {
        case .distances:
```

2024-05-09 11:19 UTC, 0Hooni commented on Honzapda/Presentation/Search/View/nonReuse/SearchMainView.swift
> +                NavigationLink(destination: SearchView(searchViewModel: searchViewModel), isActive: $searchViewModel.convertSearchPage) {
p3: 여기 인자들 줄 바꿈 해두면 좀 더 가독성 좋을것 같아요

2024-05-09 11:20 UTC, 0Hooni commented on Honzapda/Presentation/Search/View/nonReuse/SearchMainView.swift
> +                            .font(Font.custom("S-Core Dream", size: 26))
p2: font extension 사용해서 작성주시면 좋을것 같아요!

2024-05-09 11:21 UTC, 0Hooni commented on Honzapda/Presentation/Search/View/nonReuse/SearchMainView.swift
> +                                .font(Font.custom("S-CoreDream-6Bold", size: 18))
p2: 여기도 font extension 적용 안된것 같습니다

2024-05-09 11:22 UTC, youz2me requested changes
패딩이나 폰트 크기나 두께 신경써주시면 좋을 것 같아요 ~~ 수정 부탁드립니다 고생하셨으요 👍

2024-05-09 11:22 UTC, youz2me commented on Honzapda/Presentation/Curation/View/CurationResultView.swift
>                          }
두 텍스트 사이에 패딩 8정도만 부여해주세요!

2024-05-09 11:22 UTC, youz2me commented on Honzapda/Presentation/Curation/View/CurationResultView.swift
>                          }
폰트 크기도 2씩 키워주세요 ~~

2024-05-09 11:22 UTC, youz2me commented on Honzapda/Presentation/Curation/View/CurationResultView.swift
>                          }
<img width="410" alt="스크린샷 2024-05-09 오후 8 14 23" src="https://github.com/Honzapda/Honzapda_iOS/assets/80394340/0000c017-9633-4712-b5a0-e6849eed7b3e">


영업중 표시하는 컴포넌트도 추가해야 하고 주소 텍스트는 gray07로 색 바꿔주세요!

2024-05-09 11:22 UTC, youz2me commented on Honzapda/Presentation/Curation/View/CurationResultView.swift
>                          }
폰트 굵기 커스텀하시려면 `Font.custom`보다는 미리 익스텐션 적용해둔 `.sCoreDream()` 쓰시는 게 좋을 것 같습니다 ~~ 폰트 굵기도 커스텀해서 넣어주세요!

2024-05-09 11:22 UTC, youz2me commented on Honzapda/Presentation/Search/View/nonReuse/SearchMainView.swift
> +                Image("icon_search_search_fill")  // 시스템 아이콘 사용
이제는 그냥 `Image(.iconSearchSearchFill)`로 적용할 수 있다고 하더라구용 참고하십쇼!

2024-05-10 07:53 UTC, youz2me approved these changes
고생하셨습니다!

2024-05-10 09:00 UTC, 0Hooni approved these changes
LGTM

2024-05-11 04:19 UTC, merged