Design/#35 실기기 화면 최적화 및 코드 효율화
Honzapda/Honzapda_iOS pull request #41
Opened 2024-05-18 23:58 UTC by AIsiteru98

## 🔥 PR 타입 (하나 이상 선택)
- [ ] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [x] 기타 사소한 수정

## 🔗 연결된 이슈

- Connected: #35 
- [x] 이슈 해결 여부

## 📄 작업 내용

- 검은 영역 제거, ( 이는 라이트모드로 해결 가능하지만 안정적인 퍼포먼스를 위해 흰색 배경을 깔아서 해결함
- 코드 효율화 ( CurationTestViewFrame, CurationButtonFrame)
- popup의 확인 버튼에 큐레이션 기록 리셋 기능 추가

|    구현 내용    |   15 pro   |
| :-------------: | :----------: |
| GIF | <img src = "" width ="250"> |

## 💻 주요 코드 설명
`CurationPopUpView.swift`
- 뷰모델의 큐레이션 테스트 기록 초기화 (mood, atmosphare, keyword, menu
```swift
Text("테스트는 총 네 단계로 이루어져 있어요.\n테스트에서는 전 단계로 돌아갈 수 없고,\n중간에 테스트를 종료하면 저장되지 않으니 조심하세요!")
                        .font(.sCoreDream(.medium, size: 12))
                        .multilineTextAlignment(.center)
                        .foregroundColor(.gray08)
                    
                    Button {
                        print("start curation test")
                        curationViewModel.gotoTest = true
                        curationViewModel.testPopup = false
                        curationViewModel.mood = "none"
                        curationViewModel.atmosphare = "none"
                        curationViewModel.keyword = "none"
                        curationViewModel.menu = "none"
                        curationViewModel.progress = 0
```
`CurationButtonFrame``
- switch문을 활용하여 반복되는 부분을 최소화 
```swift
struct CurationTestButtonLabelCreater3: View {
    let num: Int
    
    var body: some View {
        ZStack {
            Image(imageName(for: num))
                .resizable()
                .frame(width: 99, height: 134)
                .shadow(radius: 3)
            
            Text(text(for: num))
                .font(.sCoreDream(.medium, size: 12))
                .foregroundColor(color(for: num))
                .multilineTextAlignment(.center)
                .offset(y: 20)
        }
    }
    
    private func imageName(for num: Int) -> String {
        switch num {
        case 1: return "button_curationTest_atmosphere_silent"
        case 2: return "button_curationTest_atmosphere_noisy"
        case 3: return "button_curationTest_atmosphere_hotplace"
        case 4: return "button_curationTest_atmosphere_silentFill"
        case 5: return "button_curationTest_atmosphere_noisyFill"
        case 6: return "button_curationTest_atmosphere_hotplaceFill"
        default: return ""
        }
    }
    
    private func text(for num: Int) -> String {
        switch num {
        case 1, 4: return "쾌적하고\n조용한 분위기"
        case 2, 5: return "적당한\n소음"
        case 3, 6: return "활기찬\n핫플레이스"
        default: return ""
        }
    }
    
    private func color(for num: Int) -> Color {
        switch num {
        case 1, 4: return .primary05
        case 2, 5: return .second105
        case 3, 6: return .second205
        default: return .black
        }
    }
}
```

2024-05-21 11:51 UTC, 0Hooni reviewed
이번에 코드 전반적으로 간소화가 된 부분이 인상적인것 같아요!!

수고하셨습니다👍

2024-05-21 11:51 UTC, 0Hooni commented on Honzapda/Presentation/Curation/View/CurationButtonFrame.swift
> +        case 1: return UIScreen.main.bounds.width * 0.85
이거 궁금한데 왜 1번 케이스만 0.85인지 알 수 있을까요?

2024-05-21 11:51 UTC, 0Hooni commented on Honzapda/Presentation/Curation/View/CurationButtonFrame.swift
> +    }
offset 으로 Text를 좌측으로 보내신것 같은데, 만약에 화면의 크기가 많이 작아진 경우이거나, 오히려 많이 커진 케이스에는 부자연스러운 Text위치가 될것 같아요! 

혹시 pading, alignment 들을 사용해서 Text의 위치를 잡는건 어떤가요?

2024-05-21 11:51 UTC, 0Hooni commented on Honzapda/Presentation/Curation/View/CurationButtonFrame.swift
> +                .font(Font.custom("S-CoreDream-6Bold", size: 16))
이부분은 custom font extension 적용이 안된것 같습니다☺️

2024-05-21 11:51 UTC, 0Hooni commented on Honzapda/Presentation/Curation/View/CurationMainView.swift
> +                        .font(Font.custom("S-CoreDream-6Bold", size: 20))
여기도 font extension 적용 부탁드려요!

2024-05-21 11:51 UTC, 0Hooni commented on Honzapda/Presentation/Curation/View/CurationPopUpView.swift
> +                        curationViewModel.progress = 0
별도의 initializer를 VM에 두는 방법도 가능한가요? 가능하다면 그렇게 적용해서 View를 깔끔하게 둘 수 있을것 같아요!

2024-05-27 06:24 UTC, youz2me requested changes
고생하셨습니다 ~~ 저도 일단 Request change로 넣어둘게요

2024-05-27 06:24 UTC, youz2me commented on Honzapda/Presentation/Curation/View/CurationButtonFrame.swift
> +    }
이 경우는 enum으로 case 분리해주면 더 좋을 것 같습니다!

2024-05-27 06:24 UTC, youz2me commented on Honzapda/Presentation/Curation/View/CurationMainView.swift
> +                                    .font(Font.custom("S-Core Dream", size: 16))
굵기도 같이 적용해주세요 ~~

2024-05-27 06:24 UTC, youz2me commented on Honzapda/Presentation/Curation/View/CurationMainView.swift
> +                                        .font(.custom("S-Core Dream", size: 10))
여기도 익스텐션 적용해주세요!

2024-05-27 06:24 UTC, youz2me commented on Honzapda/Presentation/Curation/View/CurationPopUpView.swift
> +                        curationViewModel.progress = 0
VM이 ObservableObject 프로토콜 준수하고 있으면 init() 함수 사용하면 될 것 같아요 ~~

```swift
class TestViewModel: ObservableObject {
    @Published var displayNumber: Int = 0
    
    init() {
        self.displayNumber = displayNumber
    }
}
```

이렇게 해주면 됩니다!

2024-05-27 06:24 UTC, youz2me commented on Honzapda/Presentation/Curation/View/CurationPopUpView.swift
>                                  .foregroundColor(Color("Primary05"))
요것도 색상 체크해주세요!

2024-05-27 06:24 UTC, youz2me commented on Honzapda/Presentation/Curation/View/CurationResultView.swift
>                  Image("image_curationmain_cafesample1") // 추후 받아온 이미지로 대체
이미지도 .imageCurationmainCafesample1 사용해서 좀 더 간편하게 작성할 수 있어요!

2024-06-02 11:48 UTC, AIsiteru98 commented on Honzapda/Presentation/Curation/View/CurationButtonFrame.swift
> +        case 1: return UIScreen.main.bounds.width * 0.85
이미지마다 그림크기가 조금씩 달라서요

2024-06-02 11:49 UTC, AIsiteru98 commented on Honzapda/Presentation/Curation/View/CurationButtonFrame.swift
> +    }
이거 수정해보겠습니다

2024-06-02 11:49 UTC, AIsiteru98 commented on Honzapda/Presentation/Curation/View/CurationButtonFrame.swift
> +                .font(Font.custom("S-CoreDream-6Bold", size: 16))
확인했습니다

2024-06-02 12:38 UTC, AIsiteru98 commented on Honzapda/Presentation/Curation/View/CurationPopUpView.swift
> +                        curationViewModel.progress = 0
이거 뷰모델에 함수 하나 만들어서 해결했습니다.

2024-06-02 17:20 UTC, AIsiteru98 commented on Honzapda/Presentation/Curation/View/CurationButtonFrame.swift
> +    }
이거는 호출 방식떄문에 일단 냅두겠습니다

2024-06-02 17:21 UTC, AIsiteru98 commented on Honzapda/Presentation/Curation/View/CurationMainView.swift
> +                                    .font(Font.custom("S-Core Dream", size: 16))
확인했습니다

2024-06-02 17:22 UTC, AIsiteru98 commented on Honzapda/Presentation/Curation/View/CurationMainView.swift
> +                                        .font(.custom("S-Core Dream", size: 10))
확인했습니당

2024-06-02 17:32 UTC, AIsiteru98 commented on Honzapda/Presentation/Curation/View/CurationButtonFrame.swift
> +        case 1: return UIScreen.main.bounds.width * 0.85
@youz2me 이거 확인점 해다오

2024-06-02 17:32 UTC, AIsiteru98 commented on Honzapda/Presentation/Curation/View/CurationResultView.swift
>                  Image("image_curationmain_cafesample1") // 추후 받아온 이미지로 대체
해당 부분은 API작업할 떄 처리해보겠습니다.

2024-06-02 17:42 UTC, AIsiteru98 reviewed
리뷰 반영했습니다 확인점여

2024-06-02 17:42 UTC, AIsiteru98 commented on Honzapda/Presentation/Curation/ViewModel/CurationViewModel.swift
리뷰 반영

2024-06-02 17:42 UTC, AIsiteru98 commented on Honzapda/Presentation/Curation/View/CurationButtonFrame.swift
폰트, 색상, 반복되는 코드 효율화, 오프셋 제거

2024-06-03 10:32 UTC, youz2me commented on Honzapda/Presentation/Curation/View/CurationButtonFrame.swift
> +        case 1: return UIScreen.main.bounds.width * 0.85
이미지 크기 문제면 그냥 이미지에 `.resizable()` 추가하면 되지 않을까요?? 굳이 크기 지정해줄 필요가 없어보이긴 합니당

2024-06-03 15:17 UTC, 0Hooni reviewed
변경사항 하나 있는데 이부분은 맥구 설계의도와 제가 이해한 의도랑 다를수 있어서 별도로 `Request Change`로 남기진 않았습니다!

혹시 제가 설계의도를 제대로 파악하지 못한것이라면 코멘트 피드백에 저 태그해서 달아주시면 이해해두고 있겠습니다☺️

수고 많으셨습니다!👍

2024-06-03 15:17 UTC, 0Hooni commented on Honzapda/Presentation/Curation/ViewModel/CurationViewModel.swift
> +    }
이부분 init 함수를 별도로 만드는게 아니라 class 자체 init으로 하시는게 좋을거같아요!
```swift
init() {
    mood = "none"
    atmosphare = "none"
    keyword = "none"
    menu = "none"
    progress = 0
}
```

아마 이렇게 선언하시고 사용하실때는 
```swift
/// init을 사용하는 방식
@ObservableObject var curationViewModel = CurationViewModel()
/// 기존 방식
CurationViewModel.initalizeCurationResult()
```
이렇게 이용하시면 바로 호출이 돼서 기존에 사용하시는 방법을 대체할 수 있을뿐더러 생성과 초기화함수를 별도로 돌리는 현재 방식보다 한줄의 단축에도 도움이 될 것 같아요!

2024-09-06 07:24 UTC, youz2me approved these changes
LGTM!

2025-03-21 08:36 UTC, merged