[Feat] #49 로그인 api연결 완료
Honzapda/Honzapda_iOS pull request #50
Opened 2024-08-28 07:50 UTC by AIsiteru98

## 🔥 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## 🔗 연결된 이슈

- Connected: #49 
- [ ] 이슈 해결 여부 - 진행중

추후 업데이트 예정
- [ ] 로그인 시 홈 뷰로 넘어가도록 변경 (아직 홈 뷰가 디벨롭에 올라와있지 않아서 미룸)
- [ ] 애플 로그인
- [ ] 그 외 사소한 문제 발생 시 chore로 추가 업뎃

## 📄 작업 내용
- 로그인 api 연결 완료
- 화면 구성

|    구현 내용    |   15 pro   |
| :-------------: | :----------: |
| GIF | <img src = "" width ="250"> |
![image](https://github.com/user-attachments/assets/58cca65b-efa7-42bf-af64-b224e6f1a708)

## 💻 주요 코드 설명
`CommonRequestModel`
- 모든 api에 공통적으로 적용되는 응답 모델 설정
- result 프로퍼티에 저장될 응답 결과 모델을 각 뷰의 모델폴더에 작성 후 ResultType으로 지정하여 사용 가능
- 글로벌/ 모델/ CommonRequestModel 에 작성
- 추후 언급시 CRM으로 작성

```swift
struct CommonResponseModel<ResultType: Decodable>: Decodable {
    let isSuccess: Bool
    let code: String
    let message: String
    let result: ResultType
}
```
`LoginModel.swift`
- 로그인에 사용되는 요청값(바디에 들어갈 내용을 담은 구조체)
- 로그인의 Response Result에 사용되는 결과 모델
```swift
import Foundation

struct LoginRequestModel: Codable {
    let email: String
    let password: String
}

struct LoginResponseResult: Codable {
    let id: Int
    let name: String
    let profileImage: String
    let email: String
    let signUpType: String
}
```
`코드 설명할 파일 이름 (ex: HomeView)`
- 어쩌구저쩌구
```swift
class LoginViewModel: ObservableObject {
.... ....
// 응답값을 저장하기 위한 프로퍼티 -> 값이 없으면 로그인 되어있지 않은 상태 값이 있으면 로그인 된 상태
    @Published var loginData: LoginResponseResult? = nil

    // api호출 후에 작동하는 함수, 정상적으로 로그인 성공 시 로그인 정보를 loginData 프로퍼티에 저장
    private func updateLoginData(newData: LoginResponseResult) { 
        self.loginData = newData
        print(self.loginData)
    } 
    // 로그인 API호출 함수
    func API_IdPwLogin(email: String, passward: String, completion: @escaping () -> Void) {
        APIManager.shared.postData(urlEndpointString: Constant.authLogin, // 기존에 static으로 저장된 엔드포인트 사용
                                   responseDataType: CommonResponseModel<LoginResponseResult>.self, // CRM에 LoginResponseResult를 응답값으로 설정하여 지정
                                   requestDataType: LoginRequestModel.self, // 요청 데이터 모델 지정
                                   parameter: LoginRequestModel(email: email, password: passward)) { response in
            //TODO: 여기서 메인 스레드에 영향을 미쳐서 뷰를 변경시켜야 함.
            DispatchQueue.main.async {
                if response.isSuccess {
//                    print("Login Success!")
//                    print("Response Code: \(response.code)")
//                    print("Message: \(response.message)")
//                    print("User ID: \(response.result.id)")
//                    print("User Name: \(response.result.name)")
//                    print("Profile Image URL: \(response.result.profileImage)")
//                    print("User Email: \(response.result.email)")
//                    print("Sign Up Type: \(response.result.signUpType)")
                    self.updateLoginData(newData: response.result) //성공 시에만 로그인 데이터 업데이트
                    
                } else {
                    print("Login Failed. Code: \(response.code), Message: \(response.message)")
// 실패 시 오류 콘솔로그로 전달
                }
                completion() // callback함수로 적용
            }
        }
    }
}
```

## 📚 참고자료

## 👀 기타 더 이야기해볼 점
자동 로그인은 어떻게 처리하는 게 좋을지?
애플 로그인 시는 로그인 처리를 어떻게 변경해야 할까?

2024-08-28 08:41 UTC, 0Hooni reviewed
제가 컨펌할건 아닌것 같아서 코멘트로만 남겨요!! 필요하시다면 컴펌으로 변경할게요☺️

수고 많으셨습니다👍

2024-08-28 08:41 UTC, 0Hooni commented on Honzapda/Global/View/GrayOutlineButton.swift
> +    @Binding var selectedCount: Int
이거 혹시 용도가 뭔지 알려주실 수 있을까요?

2024-08-28 08:41 UTC, 0Hooni commented on Honzapda/Network/NetworkManager.swift
> +                    }
디버깅할때 확인하는 용도로 넣으신것 같은데 테스팅으로 넘기면 좋을거같아요

2024-08-28 08:41 UTC, 0Hooni commented on Honzapda/Presentation/Onboarding/View/Main/SignUpCurationView.swift
> +    @State private var selectedCount = 0
아마 이부분때문에 아까 커스텀뷰에 바인딩을 추가하신것 같은데 

혹시 해당 뷰에있는 모델, 뷰모델을 이용해서 처리할 수 있으면 그게 더 아키텍쳐 패턴에 적합해보입니다👍

2024-08-28 08:41 UTC, 0Hooni commented on Honzapda/Presentation/Onboarding/View/Main/TermView.swift
> +                TermDetailView(termViewModel: termViewModel)
네이밍 수정 좋네요☺️

2024-08-28 08:41 UTC, 0Hooni commented on Honzapda/Presentation/Onboarding/ViewModel/LoginViewModel.swift
> +            //TODO: 여기서 메인 스레드에 영향을 미쳐서 뷰를 변경시켜야 함.
제가 학습했던바로는 메인스레드는 UI업데이트와 관련된 동작을 처리하는게 좋다고 알고있어요!!

우선 용도에 맞게 해당 작업은 Global큐에서 진행하면 좋다 생각합니다!

추가로 이게 해결방법일지는 확실하진 않지만 글로벌큐로 진행해도 같은 문제가 발생하는지도 궁금하네요

2024-08-30 11:57 UTC, AIsiteru98 commented on Honzapda/Presentation/Onboarding/View/Main/SignUpCurationView.swift
> +    @State private var selectedCount = 0
오 그렇긴한데 이건 제가 건든 부분이 아니라서ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
반영해 보겠습니다

2024-08-31 04:30 UTC, youz2me requested changes
고생하셨습니다. 궁금하신 점 있으시면 물어봐주세요!

2024-08-31 04:30 UTC, youz2me commented on Honzapda/Presentation/Onboarding/Model/LoginModel.swift
> +struct LoginResponseResult: Codable {
이 네이밍도 LoginResponseModel이면 더 통일성 있을 것 같네요.

2024-08-31 04:30 UTC, youz2me commented on Honzapda/Network/NetworkModel.swift
> +}
APIModel이 있는데 CommonRequestModel을 추가한 이유가 있을까요?

2024-08-31 04:30 UTC, youz2me commented on Honzapda/Presentation/Onboarding/View/Main/SignUpCurationView.swift
> +                        print("DEBUG: 취향 생성 완료하기")
디버그문은 최대한 삭제해주세요!

2024-08-31 04:30 UTC, youz2me commented on Honzapda/Presentation/Onboarding/View/Main/SignUpCurationView.swift
> +                    }
삼항연산자로도 처리해볼 수 있을 것 같네용

2024-08-31 04:30 UTC, youz2me commented on Honzapda/Presentation/Onboarding/View/Main/SignUpEmailTypeView.swift
> +                        // No Action
뷰를 다시 그리는 것보다 Button의 enable 상태를 변경만 해줘도 괜찮을 것 같습니다.

2024-08-31 04:30 UTC, youz2me commented on Honzapda/Presentation/Onboarding/View/Main/SignUpEmailTypeView.swift
> +            }
이것도 삼항연산자로 처리해볼 수 있을 것 같네용

2024-08-31 04:30 UTC, youz2me commented on Honzapda/Presentation/Onboarding/View/Main/SignUpPasswordCheckTypeView.swift
> +                if IsPasswordSame(pw: inputText) == "비밀번호가 일치해요! :)" {
String을 반환하는 이유가 있을까요? 저는 Bool을 반환하면 더 간편하게 처리할 수 있을 것 같습니다.

2024-08-31 04:30 UTC, youz2me commented on Honzapda/Presentation/Onboarding/View/Main/SignUpPasswordCheckTypeView.swift
> +            }
이것도 삼항연산자로 한번에 처리할 수 있을 듯 하네요.

2024-08-31 04:30 UTC, youz2me commented on Honzapda/Presentation/Onboarding/View/Main/SignUpPasswordTypeView.swift
> +            let isValidPasswordForm = passwordPredicate.evaluate(with: password)    // 비밀번호 형식 체크
이 부분도 뷰모델로 뺄 수 있지 않을까... 싶습니다

2024-08-31 04:30 UTC, youz2me commented on Honzapda/Presentation/Onboarding/ViewModel/LoginViewModel.swift
> +    func API_IdPwLogin(email: String, passward: String, completion: @escaping () -> Void) {
저희 함수명 컨벤션이 카멜케이스를 따르고 있어서 함수명 수정이 필요해 보입니다.

2024-08-31 04:30 UTC, youz2me commented on Honzapda/Presentation/Onboarding/ViewModel/LoginViewModel.swift
> +//                    print("Sign Up Type: \(response.result.signUpType)")
필요없는 print 문은 삭제해주세요!

2024-09-06 07:23 UTC, youz2me approved these changes
고생하셨습니다! 👍

2024-09-08 05:46 UTC, merged